module Momento
  module Cache
    class Configuration
      def with_timeout: -> Configuration

      def with_num_connections: -> Configuration

      def with_transport_strategy: -> Configuration

      attr_reader transport_strategy: TransportStrategy
    end
  end
end
