require:
  - 'rubocop-performance'
  - 'rubocop-rake'
  - 'rubocop-rspec'

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    # Generated protobuf files
    - 'lib/momento/generated/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Lint/AmbiguousBlockAssociation:
  # For rspec
  AllowedPatterns: ['change']

Metrics/MethodLength:
  Max: 15

# The rspec defaults are way too tight.
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Max: 10
# I disagree with this one. It should be clear you're using the subject.
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

# end.method looks really weird, and the other styles are too fussy
Style/BlockDelimiters:
  Enabled: false

# Enable it if they ever do anything with it.
Style/FrozenStringLiteralComment:
  Enabled: false

# In a language which returns it's last evaluated expression,
# it's useful to know when you intend to return vs when you don't.
Style/RedundantReturn:
  Enabled: false

# Too fussy, doesn't solve a problem
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

# I find the %x arrays hard to remember.
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/momento/generated/**/*'

Style/Documentation:
  Exclude:
    - 'lib/momento/generated/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/momento/generated/**/*'
