module Momento
  class CredentialProvider
    def self.from_env_var: -> CredentialProvider

    def self.from_string: -> CredentialProvider

    attr_reader api_key: String
    attr_reader cache_endpoint: String
    attr_reader control_endpoint: String
  end
end
