# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cacheclient.proto for package 'cache_client'

require 'grpc'
require 'cacheclient_pb'

module CacheClient
  module Scs
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cache_client.Scs'

      rpc :Get, ::CacheClient::GetRequest, ::CacheClient::GetResponse
      rpc :Set, ::CacheClient::SetRequest, ::CacheClient::SetResponse
      rpc :Delete, ::CacheClient::DeleteRequest, ::CacheClient::DeleteResponse
      rpc :DictionaryGet, ::CacheClient::DictionaryGetRequest, ::CacheClient::DictionaryGetResponse
      rpc :DictionaryFetch, ::CacheClient::DictionaryFetchRequest, ::CacheClient::DictionaryFetchResponse
      rpc :DictionarySet, ::CacheClient::DictionarySetRequest, ::CacheClient::DictionarySetResponse
      rpc :DictionaryIncrement, ::CacheClient::DictionaryIncrementRequest, ::CacheClient::DictionaryIncrementResponse
      rpc :DictionaryDelete, ::CacheClient::DictionaryDeleteRequest, ::CacheClient::DictionaryDeleteResponse
      rpc :SetFetch, ::CacheClient::SetFetchRequest, ::CacheClient::SetFetchResponse
      rpc :SetUnion, ::CacheClient::SetUnionRequest, ::CacheClient::SetUnionResponse
      rpc :SetDifference, ::CacheClient::SetDifferenceRequest, ::CacheClient::SetDifferenceResponse
      rpc :ListPushFront, ::CacheClient::ListPushFrontRequest, ::CacheClient::ListPushFrontResponse
      rpc :ListPushBack, ::CacheClient::ListPushBackRequest, ::CacheClient::ListPushBackResponse
      rpc :ListPopFront, ::CacheClient::ListPopFrontRequest, ::CacheClient::ListPopFrontResponse
      rpc :ListPopBack, ::CacheClient::ListPopBackRequest, ::CacheClient::ListPopBackResponse
      rpc :ListErase, ::CacheClient::ListEraseRequest, ::CacheClient::ListEraseResponse
      rpc :ListRemove, ::CacheClient::ListRemoveRequest, ::CacheClient::ListRemoveResponse
      rpc :ListFetch, ::CacheClient::ListFetchRequest, ::CacheClient::ListFetchResponse
      rpc :ListLength, ::CacheClient::ListLengthRequest, ::CacheClient::ListLengthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
