# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cacheclient.proto", :syntax => :proto3) do
    add_message "cache_client._GetRequest" do
      optional :cache_key, :bytes, 1
    end
    add_message "cache_client._GetResponse" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :cache_body, :bytes, 2
      optional :message, :string, 3
    end
    add_message "cache_client._DeleteRequest" do
      optional :cache_key, :bytes, 1
    end
    add_message "cache_client._DeleteResponse" do
    end
    add_message "cache_client._SetRequest" do
      optional :cache_key, :bytes, 1
      optional :cache_body, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
    end
    add_message "cache_client._SetResponse" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :message, :string, 2
    end
    add_message "cache_client._DictionaryGetRequest" do
      optional :dictionary_name, :bytes, 1
      repeated :fields, :bytes, 2
    end
    add_message "cache_client._DictionaryGetResponse" do
      oneof :dictionary do
        optional :found, :message, 1, "cache_client._DictionaryGetResponse._Found"
        optional :missing, :message, 2, "cache_client._DictionaryGetResponse._Missing"
      end
    end
    add_message "cache_client._DictionaryGetResponse._DictionaryGetResponsePart" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :cache_body, :bytes, 2
    end
    add_message "cache_client._DictionaryGetResponse._Found" do
      repeated :items, :message, 1, "cache_client._DictionaryGetResponse._DictionaryGetResponsePart"
    end
    add_message "cache_client._DictionaryGetResponse._Missing" do
    end
    add_message "cache_client._DictionaryFetchRequest" do
      optional :dictionary_name, :bytes, 1
    end
    add_message "cache_client._DictionaryFieldValuePair" do
      optional :field, :bytes, 1
      optional :value, :bytes, 2
    end
    add_message "cache_client._DictionaryFetchResponse" do
      oneof :dictionary do
        optional :found, :message, 1, "cache_client._DictionaryFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._DictionaryFetchResponse._Missing"
      end
    end
    add_message "cache_client._DictionaryFetchResponse._Found" do
      repeated :items, :message, 1, "cache_client._DictionaryFieldValuePair"
    end
    add_message "cache_client._DictionaryFetchResponse._Missing" do
    end
    add_message "cache_client._DictionarySetRequest" do
      optional :dictionary_name, :bytes, 1
      repeated :items, :message, 2, "cache_client._DictionaryFieldValuePair"
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
    end
    add_message "cache_client._DictionarySetResponse" do
    end
    add_message "cache_client._DictionaryIncrementRequest" do
      optional :dictionary_name, :bytes, 1
      optional :field, :bytes, 2
      optional :amount, :int64, 3
      optional :ttl_milliseconds, :uint64, 4
      optional :refresh_ttl, :bool, 5
    end
    add_message "cache_client._DictionaryIncrementResponse" do
      optional :value, :int64, 1
    end
    add_message "cache_client._DictionaryDeleteRequest" do
      optional :dictionary_name, :bytes, 1
      oneof :delete do
        optional :some, :message, 2, "cache_client._DictionaryDeleteRequest.Some"
        optional :all, :message, 3, "cache_client._DictionaryDeleteRequest.All"
      end
    end
    add_message "cache_client._DictionaryDeleteRequest.Some" do
      repeated :fields, :bytes, 1
    end
    add_message "cache_client._DictionaryDeleteRequest.All" do
    end
    add_message "cache_client._DictionaryDeleteResponse" do
    end
    add_message "cache_client._SetFetchRequest" do
      optional :set_name, :bytes, 1
    end
    add_message "cache_client._SetFetchResponse" do
      oneof :set do
        optional :found, :message, 1, "cache_client._SetFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._SetFetchResponse._Missing"
      end
    end
    add_message "cache_client._SetFetchResponse._Found" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetFetchResponse._Missing" do
    end
    add_message "cache_client._SetUnionRequest" do
      optional :set_name, :bytes, 1
      repeated :elements, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
    end
    add_message "cache_client._SetUnionResponse" do
    end
    add_message "cache_client._SetDifferenceRequest" do
      optional :set_name, :bytes, 1
      oneof :difference do
        optional :minuend, :message, 2, "cache_client._SetDifferenceRequest._Minuend"
        optional :subtrahend, :message, 3, "cache_client._SetDifferenceRequest._Subtrahend"
      end
    end
    add_message "cache_client._SetDifferenceRequest._Minuend" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend" do
      oneof :subtrahend_set do
        optional :set, :message, 1, "cache_client._SetDifferenceRequest._Subtrahend._Set"
        optional :identity, :message, 2, "cache_client._SetDifferenceRequest._Subtrahend._Identity"
      end
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend._Set" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend._Identity" do
    end
    add_message "cache_client._SetDifferenceResponse" do
      oneof :set do
        optional :found, :message, 1, "cache_client._SetDifferenceResponse._Found"
        optional :missing, :message, 2, "cache_client._SetDifferenceResponse._Missing"
      end
    end
    add_message "cache_client._SetDifferenceResponse._Found" do
    end
    add_message "cache_client._SetDifferenceResponse._Missing" do
    end
    add_message "cache_client._ListPushFrontRequest" do
      optional :list_name, :bytes, 1
      optional :value, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
      proto3_optional :truncate_back_to_size, :uint32, 5
    end
    add_message "cache_client._ListPushFrontResponse" do
      optional :list_length, :uint32, 1
    end
    add_message "cache_client._ListPushBackRequest" do
      optional :list_name, :bytes, 1
      optional :value, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
      proto3_optional :truncate_front_to_size, :uint32, 5
    end
    add_message "cache_client._ListPushBackResponse" do
      optional :list_length, :uint32, 1
    end
    add_message "cache_client._ListPopFrontRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListPopFrontResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListPopFrontResponse._Found"
        optional :missing, :message, 2, "cache_client._ListPopFrontResponse._Missing"
      end
    end
    add_message "cache_client._ListPopFrontResponse._Found" do
      optional :front, :bytes, 1
    end
    add_message "cache_client._ListPopFrontResponse._Missing" do
    end
    add_message "cache_client._ListPopBackRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListPopBackResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListPopBackResponse._Found"
        optional :missing, :message, 2, "cache_client._ListPopBackResponse._Missing"
      end
    end
    add_message "cache_client._ListPopBackResponse._Found" do
      optional :back, :bytes, 1
    end
    add_message "cache_client._ListPopBackResponse._Missing" do
    end
    add_message "cache_client._ListRange" do
      optional :begin_index, :uint32, 1
      optional :count, :uint32, 2
    end
    add_message "cache_client._ListEraseRequest" do
      optional :list_name, :bytes, 1
      oneof :erase do
        optional :some, :message, 2, "cache_client._ListEraseRequest._ListRanges"
        optional :all, :message, 3, "cache_client._ListEraseRequest._All"
      end
    end
    add_message "cache_client._ListEraseRequest._All" do
    end
    add_message "cache_client._ListEraseRequest._ListRanges" do
      repeated :ranges, :message, 1, "cache_client._ListRange"
    end
    add_message "cache_client._ListEraseResponse" do
    end
    add_message "cache_client._ListRemoveRequest" do
      optional :list_name, :bytes, 1
      oneof :remove do
        optional :all_elements_with_value, :bytes, 2
      end
    end
    add_message "cache_client._ListRemoveResponse" do
    end
    add_message "cache_client._ListFetchRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListFetchResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._ListFetchResponse._Missing"
      end
    end
    add_message "cache_client._ListFetchResponse._Found" do
      repeated :values, :bytes, 1
    end
    add_message "cache_client._ListFetchResponse._Missing" do
    end
    add_message "cache_client._ListLengthRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListLengthResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListLengthResponse._Found"
        optional :missing, :message, 2, "cache_client._ListLengthResponse._Missing"
      end
    end
    add_message "cache_client._ListLengthResponse._Found" do
      optional :length, :uint32, 1
    end
    add_message "cache_client._ListLengthResponse._Missing" do
    end
    add_enum "cache_client.ECacheResult" do
      value :Invalid, 0
      value :Ok, 1
      value :Hit, 2
      value :Miss, 3
    end
  end
end

module CacheClient
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._GetRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._GetResponse").msgclass
  DeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DeleteRequest").msgclass
  DeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DeleteResponse").msgclass
  SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetRequest").msgclass
  SetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetResponse").msgclass
  DictionaryGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetRequest").msgclass
  DictionaryGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse").msgclass
  DictionaryGetResponse::DictionaryGetResponsePart = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._DictionaryGetResponsePart").msgclass
  DictionaryGetResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._Found").msgclass
  DictionaryGetResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._Missing").msgclass
  DictionaryFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchRequest").msgclass
  DictionaryFieldValuePair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFieldValuePair").msgclass
  DictionaryFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse").msgclass
  DictionaryFetchResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse._Found").msgclass
  DictionaryFetchResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse._Missing").msgclass
  DictionarySetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionarySetRequest").msgclass
  DictionarySetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionarySetResponse").msgclass
  DictionaryIncrementRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryIncrementRequest").msgclass
  DictionaryIncrementResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryIncrementResponse").msgclass
  DictionaryDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest").msgclass
  DictionaryDeleteRequest::Some = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest.Some").msgclass
  DictionaryDeleteRequest::All = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest.All").msgclass
  DictionaryDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteResponse").msgclass
  SetFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchRequest").msgclass
  SetFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse").msgclass
  SetFetchResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse._Found").msgclass
  SetFetchResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse._Missing").msgclass
  SetUnionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetUnionRequest").msgclass
  SetUnionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetUnionResponse").msgclass
  SetDifferenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest").msgclass
  SetDifferenceRequest::Minuend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Minuend").msgclass
  SetDifferenceRequest::Subtrahend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend").msgclass
  SetDifferenceRequest::Subtrahend::Set = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend._Set").msgclass
  SetDifferenceRequest::Subtrahend::Identity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend._Identity").msgclass
  SetDifferenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse").msgclass
  SetDifferenceResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse._Found").msgclass
  SetDifferenceResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse._Missing").msgclass
  ListPushFrontRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushFrontRequest").msgclass
  ListPushFrontResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushFrontResponse").msgclass
  ListPushBackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushBackRequest").msgclass
  ListPushBackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushBackResponse").msgclass
  ListPopFrontRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontRequest").msgclass
  ListPopFrontResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse").msgclass
  ListPopFrontResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse._Found").msgclass
  ListPopFrontResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse._Missing").msgclass
  ListPopBackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackRequest").msgclass
  ListPopBackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse").msgclass
  ListPopBackResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse._Found").msgclass
  ListPopBackResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse._Missing").msgclass
  ListRange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRange").msgclass
  ListEraseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest").msgclass
  ListEraseRequest::All = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest._All").msgclass
  ListEraseRequest::ListRanges = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest._ListRanges").msgclass
  ListEraseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseResponse").msgclass
  ListRemoveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRemoveRequest").msgclass
  ListRemoveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRemoveResponse").msgclass
  ListFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchRequest").msgclass
  ListFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse").msgclass
  ListFetchResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse._Found").msgclass
  ListFetchResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse._Missing").msgclass
  ListLengthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthRequest").msgclass
  ListLengthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse").msgclass
  ListLengthResponse::Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse._Found").msgclass
  ListLengthResponse::Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse._Missing").msgclass
  ECacheResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client.ECacheResult").enummodule
end
