# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cacheclient.proto", :syntax => :proto3) do
    add_message "cache_client._GetRequest" do
      optional :cache_key, :bytes, 1
    end
    add_message "cache_client._GetResponse" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :cache_body, :bytes, 2
      optional :message, :string, 3
    end
    add_message "cache_client._DeleteRequest" do
      optional :cache_key, :bytes, 1
    end
    add_message "cache_client._DeleteResponse" do
    end
    add_message "cache_client._SetRequest" do
      optional :cache_key, :bytes, 1
      optional :cache_body, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
    end
    add_message "cache_client._SetResponse" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :message, :string, 2
    end
    add_message "cache_client._DictionaryGetRequest" do
      optional :dictionary_name, :bytes, 1
      repeated :fields, :bytes, 2
    end
    add_message "cache_client._DictionaryGetResponse" do
      oneof :dictionary do
        optional :found, :message, 1, "cache_client._DictionaryGetResponse._Found"
        optional :missing, :message, 2, "cache_client._DictionaryGetResponse._Missing"
      end
    end
    add_message "cache_client._DictionaryGetResponse._DictionaryGetResponsePart" do
      optional :result, :enum, 1, "cache_client.ECacheResult"
      optional :cache_body, :bytes, 2
    end
    add_message "cache_client._DictionaryGetResponse._Found" do
      repeated :items, :message, 1, "cache_client._DictionaryGetResponse._DictionaryGetResponsePart"
    end
    add_message "cache_client._DictionaryGetResponse._Missing" do
    end
    add_message "cache_client._DictionaryFetchRequest" do
      optional :dictionary_name, :bytes, 1
    end
    add_message "cache_client._DictionaryFieldValuePair" do
      optional :field, :bytes, 1
      optional :value, :bytes, 2
    end
    add_message "cache_client._DictionaryFetchResponse" do
      oneof :dictionary do
        optional :found, :message, 1, "cache_client._DictionaryFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._DictionaryFetchResponse._Missing"
      end
    end
    add_message "cache_client._DictionaryFetchResponse._Found" do
      repeated :items, :message, 1, "cache_client._DictionaryFieldValuePair"
    end
    add_message "cache_client._DictionaryFetchResponse._Missing" do
    end
    add_message "cache_client._DictionarySetRequest" do
      optional :dictionary_name, :bytes, 1
      repeated :items, :message, 2, "cache_client._DictionaryFieldValuePair"
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
    end
    add_message "cache_client._DictionarySetResponse" do
    end
    add_message "cache_client._DictionaryIncrementRequest" do
      optional :dictionary_name, :bytes, 1
      optional :field, :bytes, 2
      optional :amount, :int64, 3
      optional :ttl_milliseconds, :uint64, 4
      optional :refresh_ttl, :bool, 5
    end
    add_message "cache_client._DictionaryIncrementResponse" do
      optional :value, :int64, 1
    end
    add_message "cache_client._DictionaryDeleteRequest" do
      optional :dictionary_name, :bytes, 1
      oneof :delete do
        optional :some, :message, 2, "cache_client._DictionaryDeleteRequest.Some"
        optional :all, :message, 3, "cache_client._DictionaryDeleteRequest.All"
      end
    end
    add_message "cache_client._DictionaryDeleteRequest.Some" do
      repeated :fields, :bytes, 1
    end
    add_message "cache_client._DictionaryDeleteRequest.All" do
    end
    add_message "cache_client._DictionaryDeleteResponse" do
    end
    add_message "cache_client._SetFetchRequest" do
      optional :set_name, :bytes, 1
    end
    add_message "cache_client._SetFetchResponse" do
      oneof :set do
        optional :found, :message, 1, "cache_client._SetFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._SetFetchResponse._Missing"
      end
    end
    add_message "cache_client._SetFetchResponse._Found" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetFetchResponse._Missing" do
    end
    add_message "cache_client._SetUnionRequest" do
      optional :set_name, :bytes, 1
      repeated :elements, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
    end
    add_message "cache_client._SetUnionResponse" do
    end
    add_message "cache_client._SetDifferenceRequest" do
      optional :set_name, :bytes, 1
      oneof :difference do
        optional :minuend, :message, 2, "cache_client._SetDifferenceRequest._Minuend"
        optional :subtrahend, :message, 3, "cache_client._SetDifferenceRequest._Subtrahend"
      end
    end
    add_message "cache_client._SetDifferenceRequest._Minuend" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend" do
      oneof :subtrahend_set do
        optional :set, :message, 1, "cache_client._SetDifferenceRequest._Subtrahend._Set"
        optional :identity, :message, 2, "cache_client._SetDifferenceRequest._Subtrahend._Identity"
      end
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend._Set" do
      repeated :elements, :bytes, 1
    end
    add_message "cache_client._SetDifferenceRequest._Subtrahend._Identity" do
    end
    add_message "cache_client._SetDifferenceResponse" do
      oneof :set do
        optional :found, :message, 1, "cache_client._SetDifferenceResponse._Found"
        optional :missing, :message, 2, "cache_client._SetDifferenceResponse._Missing"
      end
    end
    add_message "cache_client._SetDifferenceResponse._Found" do
    end
    add_message "cache_client._SetDifferenceResponse._Missing" do
    end
    add_message "cache_client._ListPushFrontRequest" do
      optional :list_name, :bytes, 1
      optional :value, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
      proto3_optional :truncate_back_to_size, :uint32, 5
    end
    add_message "cache_client._ListPushFrontResponse" do
      optional :list_length, :uint32, 1
    end
    add_message "cache_client._ListPushBackRequest" do
      optional :list_name, :bytes, 1
      optional :value, :bytes, 2
      optional :ttl_milliseconds, :uint64, 3
      optional :refresh_ttl, :bool, 4
      proto3_optional :truncate_front_to_size, :uint32, 5
    end
    add_message "cache_client._ListPushBackResponse" do
      optional :list_length, :uint32, 1
    end
    add_message "cache_client._ListPopFrontRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListPopFrontResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListPopFrontResponse._Found"
        optional :missing, :message, 2, "cache_client._ListPopFrontResponse._Missing"
      end
    end
    add_message "cache_client._ListPopFrontResponse._Found" do
      optional :front, :bytes, 1
    end
    add_message "cache_client._ListPopFrontResponse._Missing" do
    end
    add_message "cache_client._ListPopBackRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListPopBackResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListPopBackResponse._Found"
        optional :missing, :message, 2, "cache_client._ListPopBackResponse._Missing"
      end
    end
    add_message "cache_client._ListPopBackResponse._Found" do
      optional :back, :bytes, 1
    end
    add_message "cache_client._ListPopBackResponse._Missing" do
    end
    add_message "cache_client._ListRange" do
      optional :begin_index, :uint32, 1
      optional :count, :uint32, 2
    end
    add_message "cache_client._ListEraseRequest" do
      optional :list_name, :bytes, 1
      oneof :erase do
        optional :some, :message, 2, "cache_client._ListEraseRequest._ListRanges"
        optional :all, :message, 3, "cache_client._ListEraseRequest._All"
      end
    end
    add_message "cache_client._ListEraseRequest._All" do
    end
    add_message "cache_client._ListEraseRequest._ListRanges" do
      repeated :ranges, :message, 1, "cache_client._ListRange"
    end
    add_message "cache_client._ListEraseResponse" do
    end
    add_message "cache_client._ListRemoveRequest" do
      optional :list_name, :bytes, 1
      oneof :remove do
        optional :all_elements_with_value, :bytes, 2
      end
    end
    add_message "cache_client._ListRemoveResponse" do
    end
    add_message "cache_client._ListFetchRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListFetchResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListFetchResponse._Found"
        optional :missing, :message, 2, "cache_client._ListFetchResponse._Missing"
      end
    end
    add_message "cache_client._ListFetchResponse._Found" do
      repeated :values, :bytes, 1
    end
    add_message "cache_client._ListFetchResponse._Missing" do
    end
    add_message "cache_client._ListLengthRequest" do
      optional :list_name, :bytes, 1
    end
    add_message "cache_client._ListLengthResponse" do
      oneof :list do
        optional :found, :message, 1, "cache_client._ListLengthResponse._Found"
        optional :missing, :message, 2, "cache_client._ListLengthResponse._Missing"
      end
    end
    add_message "cache_client._ListLengthResponse._Found" do
      optional :length, :uint32, 1
    end
    add_message "cache_client._ListLengthResponse._Missing" do
    end
    add_enum "cache_client.ECacheResult" do
      value :Invalid, 0
      value :Ok, 1
      value :Hit, 2
      value :Miss, 3
    end
  end
end

module CacheClient
  PB__GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._GetRequest").msgclass
  PB__GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._GetResponse").msgclass
  PB__DeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DeleteRequest").msgclass
  PB__DeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DeleteResponse").msgclass
  PB__SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetRequest").msgclass
  PB__SetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetResponse").msgclass
  PB__DictionaryGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetRequest").msgclass
  PB__DictionaryGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse").msgclass
  PB__DictionaryGetResponse::PB__DictionaryGetResponsePart = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._DictionaryGetResponsePart").msgclass
  PB__DictionaryGetResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._Found").msgclass
  PB__DictionaryGetResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryGetResponse._Missing").msgclass
  PB__DictionaryFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchRequest").msgclass
  PB__DictionaryFieldValuePair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFieldValuePair").msgclass
  PB__DictionaryFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse").msgclass
  PB__DictionaryFetchResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse._Found").msgclass
  PB__DictionaryFetchResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryFetchResponse._Missing").msgclass
  PB__DictionarySetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionarySetRequest").msgclass
  PB__DictionarySetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionarySetResponse").msgclass
  PB__DictionaryIncrementRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryIncrementRequest").msgclass
  PB__DictionaryIncrementResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryIncrementResponse").msgclass
  PB__DictionaryDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest").msgclass
  PB__DictionaryDeleteRequest::Some = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest.Some").msgclass
  PB__DictionaryDeleteRequest::All = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteRequest.All").msgclass
  PB__DictionaryDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._DictionaryDeleteResponse").msgclass
  PB__SetFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchRequest").msgclass
  PB__SetFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse").msgclass
  PB__SetFetchResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse._Found").msgclass
  PB__SetFetchResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetFetchResponse._Missing").msgclass
  PB__SetUnionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetUnionRequest").msgclass
  PB__SetUnionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetUnionResponse").msgclass
  PB__SetDifferenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest").msgclass
  PB__SetDifferenceRequest::PB__Minuend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Minuend").msgclass
  PB__SetDifferenceRequest::PB__Subtrahend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend").msgclass
  PB__SetDifferenceRequest::PB__Subtrahend::PB__Set = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend._Set").msgclass
  PB__SetDifferenceRequest::PB__Subtrahend::PB__Identity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceRequest._Subtrahend._Identity").msgclass
  PB__SetDifferenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse").msgclass
  PB__SetDifferenceResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse._Found").msgclass
  PB__SetDifferenceResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._SetDifferenceResponse._Missing").msgclass
  PB__ListPushFrontRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushFrontRequest").msgclass
  PB__ListPushFrontResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushFrontResponse").msgclass
  PB__ListPushBackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushBackRequest").msgclass
  PB__ListPushBackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPushBackResponse").msgclass
  PB__ListPopFrontRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontRequest").msgclass
  PB__ListPopFrontResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse").msgclass
  PB__ListPopFrontResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse._Found").msgclass
  PB__ListPopFrontResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopFrontResponse._Missing").msgclass
  PB__ListPopBackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackRequest").msgclass
  PB__ListPopBackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse").msgclass
  PB__ListPopBackResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse._Found").msgclass
  PB__ListPopBackResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListPopBackResponse._Missing").msgclass
  PB__ListRange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRange").msgclass
  PB__ListEraseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest").msgclass
  PB__ListEraseRequest::PB__All = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest._All").msgclass
  PB__ListEraseRequest::PB__ListRanges = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseRequest._ListRanges").msgclass
  PB__ListEraseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListEraseResponse").msgclass
  PB__ListRemoveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRemoveRequest").msgclass
  PB__ListRemoveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListRemoveResponse").msgclass
  PB__ListFetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchRequest").msgclass
  PB__ListFetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse").msgclass
  PB__ListFetchResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse._Found").msgclass
  PB__ListFetchResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListFetchResponse._Missing").msgclass
  PB__ListLengthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthRequest").msgclass
  PB__ListLengthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse").msgclass
  PB__ListLengthResponse::PB__Found = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse._Found").msgclass
  PB__ListLengthResponse::PB__Missing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client._ListLengthResponse._Missing").msgclass
  ECacheResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cache_client.ECacheResult").enummodule
end
