# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cacheclient.proto for package 'cache_client'

require 'grpc'
require 'cacheclient_pb'

module CacheClient
  module Scs
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cache_client.Scs'

      rpc :Get, ::CacheClient::_GetRequest, ::CacheClient::_GetResponse
      rpc :Set, ::CacheClient::_SetRequest, ::CacheClient::_SetResponse
      rpc :Delete, ::CacheClient::_DeleteRequest, ::CacheClient::_DeleteResponse
      rpc :DictionaryGet, ::CacheClient::_DictionaryGetRequest, ::CacheClient::_DictionaryGetResponse
      rpc :DictionaryFetch, ::CacheClient::_DictionaryFetchRequest, ::CacheClient::_DictionaryFetchResponse
      rpc :DictionarySet, ::CacheClient::_DictionarySetRequest, ::CacheClient::_DictionarySetResponse
      rpc :DictionaryIncrement, ::CacheClient::_DictionaryIncrementRequest, ::CacheClient::_DictionaryIncrementResponse
      rpc :DictionaryDelete, ::CacheClient::_DictionaryDeleteRequest, ::CacheClient::_DictionaryDeleteResponse
      rpc :SetFetch, ::CacheClient::_SetFetchRequest, ::CacheClient::_SetFetchResponse
      rpc :SetUnion, ::CacheClient::_SetUnionRequest, ::CacheClient::_SetUnionResponse
      rpc :SetDifference, ::CacheClient::_SetDifferenceRequest, ::CacheClient::_SetDifferenceResponse
      rpc :ListPushFront, ::CacheClient::_ListPushFrontRequest, ::CacheClient::_ListPushFrontResponse
      rpc :ListPushBack, ::CacheClient::_ListPushBackRequest, ::CacheClient::_ListPushBackResponse
      rpc :ListPopFront, ::CacheClient::_ListPopFrontRequest, ::CacheClient::_ListPopFrontResponse
      rpc :ListPopBack, ::CacheClient::_ListPopBackRequest, ::CacheClient::_ListPopBackResponse
      rpc :ListErase, ::CacheClient::_ListEraseRequest, ::CacheClient::_ListEraseResponse
      rpc :ListRemove, ::CacheClient::_ListRemoveRequest, ::CacheClient::_ListRemoveResponse
      rpc :ListFetch, ::CacheClient::_ListFetchRequest, ::CacheClient::_ListFetchResponse
      rpc :ListLength, ::CacheClient::_ListLengthRequest, ::CacheClient::_ListLengthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
