# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("controlclient.proto", :syntax => :proto3) do
    add_message "control_client._DeleteCacheRequest" do
      optional :cache_name, :string, 1
    end
    add_message "control_client._DeleteCacheResponse" do
    end
    add_message "control_client._CreateCacheRequest" do
      optional :cache_name, :string, 1
    end
    add_message "control_client._CreateCacheResponse" do
    end
    add_message "control_client._ListCachesRequest" do
      optional :next_token, :string, 1
    end
    add_message "control_client._Cache" do
      optional :cache_name, :string, 1
    end
    add_message "control_client._ListCachesResponse" do
      repeated :cache, :message, 1, "control_client._Cache"
      optional :next_token, :string, 2
    end
    add_message "control_client._CreateSigningKeyRequest" do
      optional :ttl_minutes, :uint32, 1
    end
    add_message "control_client._CreateSigningKeyResponse" do
      optional :key, :string, 1
      optional :expires_at, :uint64, 2
    end
    add_message "control_client._RevokeSigningKeyRequest" do
      optional :key_id, :string, 1
    end
    add_message "control_client._RevokeSigningKeyResponse" do
    end
    add_message "control_client._SigningKey" do
      optional :key_id, :string, 1
      optional :expires_at, :uint64, 2
    end
    add_message "control_client._ListSigningKeysRequest" do
      optional :next_token, :string, 1
    end
    add_message "control_client._ListSigningKeysResponse" do
      repeated :signing_key, :message, 1, "control_client._SigningKey"
      optional :next_token, :string, 2
    end
  end
end

module ControlClient
  PB__DeleteCacheRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._DeleteCacheRequest").msgclass
  PB__DeleteCacheResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._DeleteCacheResponse").msgclass
  PB__CreateCacheRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._CreateCacheRequest").msgclass
  PB__CreateCacheResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._CreateCacheResponse").msgclass
  PB__ListCachesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._ListCachesRequest").msgclass
  PB__Cache = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._Cache").msgclass
  PB__ListCachesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._ListCachesResponse").msgclass
  PB__CreateSigningKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._CreateSigningKeyRequest").msgclass
  PB__CreateSigningKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._CreateSigningKeyResponse").msgclass
  PB__RevokeSigningKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._RevokeSigningKeyRequest").msgclass
  PB__RevokeSigningKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._RevokeSigningKeyResponse").msgclass
  PB__SigningKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._SigningKey").msgclass
  PB__ListSigningKeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._ListSigningKeysRequest").msgclass
  PB__ListSigningKeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("control_client._ListSigningKeysResponse").msgclass
end
