# @private

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: controlclient.proto for package 'control_client'

require 'grpc'
require_relative 'controlclient_pb'

module Momento
  module ControlClient
    module ScsControl
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'control_client.ScsControl'

        rpc :CreateCache, ::Momento::ControlClient::CreateCacheRequest, ::Momento::ControlClient::CreateCacheResponse
        rpc :DeleteCache, ::Momento::ControlClient::DeleteCacheRequest, ::Momento::ControlClient::DeleteCacheResponse
        rpc :ListCaches, ::Momento::ControlClient::ListCachesRequest, ::Momento::ControlClient::ListCachesResponse
        rpc :CreateSigningKey, ::Momento::ControlClient::CreateSigningKeyRequest, ::Momento::ControlClient::CreateSigningKeyResponse
        rpc :RevokeSigningKey, ::Momento::ControlClient::RevokeSigningKeyRequest, ::Momento::ControlClient::RevokeSigningKeyResponse
        rpc :ListSigningKeys, ::Momento::ControlClient::ListSigningKeysRequest, ::Momento::ControlClient::ListSigningKeysResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
