name: On push or PR to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  momento-shared-build:
    runs-on: ubuntu-latest
    steps:
      - uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-performance:gemfile rubocop-rake:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v1
        with:
          project_status: official
          project_stability: alpha
          project_type: sdk
          sdk_language: Ruby
          usage_example_path: ./examples/example.rb

  test:
    # Don't test until all code is generated.
    needs: [readme]
    uses: ./.github/workflows/test.yml
    secrets:
      auth-token: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
    with:
      live: true
