name: On push to release

on:
  push:
    branches: [ release ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.7
          - 3.0
          - 3.1

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

  publish:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3

      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          branches:
            - release
          # We only want the version #.
          dry: true
          github-token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"

      - name: Show release version
        if: ${{ success() }}
        run: |
          echo $RELEASE_VERSION

      - name: Set up Ruby
        if: ${{ success() }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gem-release
        if: ${{ success() }}
        run: |
          gem install gem-release

      - name: Bump version and tag
        if: ${{ success() }}
        run: |
          gem bump -v $RELEASE_VERSION

      - uses: cadwallion/publish-rubygems-action@master
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_PUBLISH_TOKEN}}
          RELEASE_COMMAND: bundle rake release
