name: release-please

on:
  push:
    branches:
      - main

jobs:
  # Use release-please to create release PRs and manage git tags
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

  # Avoid `rake release` in the publishing step since it might try to create a git tag again
  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build gem
        run: |
          bundle exec rake build

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_PUBLISH_TOKEN }}
        run: |
          gem push pkg/*.gem

      - name: Upload artifacts to the GitHub Actions Run
        uses: actions/upload-artifact@v4
        with:
          name: gemfiles-v${{ needs.release-please.outputs.release_tag }}
          path: |
            pkg/*.gem
