name: Test matrix (reusable)

on:
  workflow_call:
    secrets:
      auth-token:
        description: 'Auth token used for live testing'
        required: false
    inputs:
      live:
        description: 'If true, run tests against a real server'
        default: false
        type: boolean
      cache-name:
        description: 'The cache name to use for live testing'
        default: ruby-integration-test-cache
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.7
          - 3.0
          - 3.1

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec
      env:
        TEST_AUTH_TOKEN: ${{ secrets.auth-token }}
        TEST_CACHE_NAME: ${{ inputs.cache-name }}-${{ matrix.ruby-version }}-${{github.sha}}
        MOMENTO_TEST_LIVE: ${{ inputs.live }}
